PMM-9073 add two tests for verifying Command type filter in QAN, case…
percona/pmm-ui-tests pull request #130
Opened 2021-11-10 00:05 UTC by ElenaFedichkina

add two tests for verifying Command type filter in QAN, cases 1054 and 1055

2021-11-12 12:22 UTC, puneet0191 submitted a review, later dismissed

2021-11-15 04:47 UTC, puneet0191 requested changes

2021-11-15 04:47 UTC, puneet0191 commented on tests/QAN/pages/qanOverviewFragment.js
> +    noResultTableText: '//div[@data-testid="table-no-data"]/h1',
you should use locate here

2021-11-15 10:37 UTC, ElenaFedichkina commented on tests/QAN/pages/qanOverviewFragment.js
> +    noResultTableText: '//div[@data-testid="table-no-data"]/h1',
edited to use locate

2021-11-17 06:19 UTC, puneet0191 approved these changes

2021-11-17 20:28 UTC, merged