PMM-8005 security checks interval tests
percona/pmm-ui-tests pull request #16
Opened 2021-05-06 15:51 UTC by yurkovychv

2021-05-11 09:18 UTC, puneet0191 approved these changes

2021-05-11 09:20 UTC, puneet0191 requested changes

2021-05-11 09:21 UTC, yurkovychv commented on tests/verifyRemoteInstances_test.js
> +Data(instances.filter((instance) => /mysql|proxysql/.test(instance.name))).Scenario(
ok, thanks

2021-05-11 12:43 UTC, IvanaBrecherova approved these changes

2021-05-12 08:16 UTC, puneet0191 approved these changes

2021-05-12 08:17 UTC, yurkovychv commented on tests/pages/api/settingsAPI.js
> +  async setCheckIntervals(intervals = this.defaultCheckIntervals) {
thanks

2021-05-12 08:17 UTC, merged