PMM-9669 IA Template Copy and New Secondary Labels QAA Testcase
percona/pmm-ui-tests pull request #227
Opened 2022-03-10 09:19 UTC by ElenaFedichkina

2022-03-16 12:00 UTC, puneet0191 submitted a review, later dismissed

2022-03-16 12:00 UTC, puneet0191 commented on tests/ia/alerts_test.js
> +    I.seeElement(alertsPage.elements.detailsSecondaryLabels, 30);
where do you verify important labels exist?

2022-03-22 11:46 UTC, puneet0191 submitted a review, later dismissed

2022-03-23 09:46 UTC, yurkovychv requested changes

2022-03-23 09:46 UTC, yurkovychv commented on tests/ia/pages/alertsPage.js
> +  checkContainingLabels(expectedLabels, alertName = null) {
please change this method to accept object with keys: `primaryLabels`, `secondaryLabels` and `alertName`

2022-03-23 09:46 UTC, yurkovychv commented on tests/ia/pages/alertsPage.js
> +const details = locate('$alert-details-wrapper');
```suggestion
const details = '$alert-details-wrapper';
```

2022-03-23 09:46 UTC, yurkovychv commented on tests/ia/pages/alertsPage.js
> +    detailsRuleExpression: locate(`${details}`).find('div').withText('Rule Expression'),
```suggestion
    detailsRuleExpression: locate(details).find('div').withText('Rule Expression'),
```

2022-03-23 09:46 UTC, yurkovychv commented on tests/ia/pages/alertsPage.js
> +    detailsRuleExpression: locate(`${details}`).find('div').withText('Rule Expression'),
same in other places

2022-03-23 09:46 UTC, yurkovychv commented on tests/ia/pages/alertsPage.js
> +    labelsCell: (alertName, text) => locate(`${alertRow(alertName)}/td[4]`).find('$chip').withText(text),
why did you change `labelsCell` locator? it is not `labelsCell` anymore in your locator. It is a `primaryLabel` locator

2022-03-25 13:37 UTC, yurkovychv approved these changes

2022-03-25 13:38 UTC, merged