PMM-9737 kill backlog
percona/pmm-ui-tests pull request #235
Opened 2022-03-21 22:27 UTC by ElenaFedichkina

created a test for case PMM-T1051 to verify PMM Settings page is opened from Home dashboard

2022-04-12 12:04 UTC, puneet0191 requested changes

2022-04-12 12:04 UTC, puneet0191 commented on tests/verifyRemoteInstances_test.js
> +  'PMM-T1087 Verify adding PostgreSQL remote instance without postgres database @instances',
I think you did the opposite of what was the expectation for this test case, we have to verify that users can add PostgreSQL remote instances even without having the default Postgres database, what you did is actually just verifying if the user-provided DB exists or not and giving back the error.

2022-04-12 12:04 UTC, puneet0191 commented on tests/upgradePMM_test.js
> +  'PMM-T1051 - Verify PMM Settings page is opened from Home dashboard @menu',
why did you add this test to upgrade test? and if we want to add this scenario for upgrade verifications, the tags don't work at all in that scenario, @menu tag tests should be inside the menu tests

2022-04-26 09:37 UTC, puneet0191 approved these changes
good stuff here, thank you

2022-04-26 09:37 UTC, puneet0191 commented on docker-compose.yml
> +  postgresremovedefaultdb:
@ElenaFedichkina could you not have a separate compose file for this specific case, you could always start the containers, in your test and kill them post that.

2022-04-26 09:37 UTC, puneet0191 commented on docker-compose.yml
> +      - "5435:5432"
or change the port to something like 6435 to avoid conflict with other tests

2022-04-27 07:21 UTC, yurkovychv approved these changes

2022-04-28 09:14 UTC, merged