PMM-10163 pgbench test
percona/pmm-ui-tests pull request #320
Opened 2022-06-19 00:53 UTC by vyarosh

2022-06-20 15:04 UTC, puneet0191 requested changes

2022-06-21 12:27 UTC, vyarosh commented on tests/metrics/verifyPostgresql_test.js
> +  'PMM-T0000 - Verify Clickhouse and PGSM view data are the same after PG_BENCH load',
done

2022-06-22 10:34 UTC, puneet0191 requested changes

2022-06-22 10:34 UTC, puneet0191 commented on tests/qa-integration/pmm_pgsm_integration_test.js
> -  'Verify Postgresql Dashboard Instance Summary has Data @not-ui-pipeline @pgsm-pmm-integration',
please add testcase name, with test case number

2022-06-22 13:31 UTC, vyarosh commented on tests/qa-integration/pmm_pgsm_integration_test.js
> -  'Verify Postgresql Dashboard Instance Summary has Data @not-ui-pipeline @pgsm-pmm-integration',
fixed

2022-06-23 15:00 UTC, merged