PMM-11523 Add tests to verify redirect to different dashboards from Home dashboard using panels
percona/pmm-ui-tests pull request #506
Opened 2023-02-02 18:23 UTC by nazarovvi

2023-02-21 11:19 UTC, puneet0191 requested changes

2023-02-21 11:19 UTC, puneet0191 commented on tests/helper/localStorageHelper.js
> -      if (window.localStorage.getItem('percona.tourTest') === true) {
why did you modify this ?

2023-03-01 10:26 UTC, nazarovvi commented on tests/helper/localStorageHelper.js
> -      if (window.localStorage.getItem('percona.tourTest') === true) {
removed it completely

2023-03-01 10:27 UTC, nazarovvi commented
![image](https://user-images.githubusercontent.com/104006070/222112853-85728c1c-81f3-43ef-b891-6517b51461a8.png)
https://pmm.cd.percona.com/job/pmm2-ui-test-nightly/1663/allure/#suites/325a1c0a7747a339b260c42990bba07a/fdb1e9b0159bb99a/

2023-03-10 12:18 UTC, puneet0191 approved these changes

2023-03-10 12:29 UTC, merged